---

- name: deploy apache web-server to node-1 and node-2
  hosts: all
  become: yes
  become_user: root

  tasks:
    - name: update ec2 virtual machines
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: install apache server
      yum:
        name: httpd
        state: latest

    - name: change directory to the html directory
      shell: cd /var/www/html

    - name: download web files from github repo
      get_url:
        url: https://github.com/adeboyefrancis/ansible-project/blob/main/homepage.zip
        dest: /var/www/html/

    - name: unzip the zip folder
      ansible.builtin.unarchive:
        src: /var/www/html/homepage.zip
        dest: /var/www/html
        remote_src: yes

    - name: copy webfiles from the homepage directory to the html directory
      copy: 
        src: /var/www/html/homepage/
        dest: /var/www/html
        remote_src: yes

    - name: remove the homepage directory
      file: 
        path: /var/www/html/homepage
        state: absent

    - name: remove the hompage.zip folder
      file: 
        path: /var/www/html/homepage.zip
        state: absent 

    - name: start apache server, if not started
      ansible.builtin.service:
        enabled: yes
        name: httpd
        state: started